version: "3"

tasks:
  run:
    desc: Run the app
    cmds:
      - GOGLAGS=-mod=mod task build && ./bin/pm

  build:
    desc: Build the app
    cmds:
      - GOGLAGS=-mod=mod go build -o bin/pm cmd/main.go
